// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoa1IKvCBkRMx8F6lQld5FXqBEao6ws_A',
    appId: '1:564519969198:web:4297e9c55bb44cc178683f',
    messagingSenderId: '564519969198',
    projectId: 'dot-auth-6d27f',
    authDomain: 'dot-auth-6d27f.firebaseapp.com',
    storageBucket: 'dot-auth-6d27f.firebasestorage.app',
    measurementId: 'G-Y6X30CP3BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbDNDO6hiSqCxbzUR01RfmE_ruzRb4FDY',
    appId: '1:564519969198:android:5f60097c7901ec0778683f',
    messagingSenderId: '564519969198',
    projectId: 'dot-auth-6d27f',
    storageBucket: 'dot-auth-6d27f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOf5F1A6xOYqJViJB0eqJQvMdKFZsWVJI',
    appId: '1:564519969198:ios:034e823f3833009578683f',
    messagingSenderId: '564519969198',
    projectId: 'dot-auth-6d27f',
    storageBucket: 'dot-auth-6d27f.firebasestorage.app',
    iosBundleId: 'com.example.dotAuthExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOf5F1A6xOYqJViJB0eqJQvMdKFZsWVJI',
    appId: '1:564519969198:ios:21e8ac15b31ed7bb78683f',
    messagingSenderId: '564519969198',
    projectId: 'dot-auth-6d27f',
    storageBucket: 'dot-auth-6d27f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoa1IKvCBkRMx8F6lQld5FXqBEao6ws_A',
    appId: '1:564519969198:web:32a3142275882d0178683f',
    messagingSenderId: '564519969198',
    projectId: 'dot-auth-6d27f',
    authDomain: 'dot-auth-6d27f.firebaseapp.com',
    storageBucket: 'dot-auth-6d27f.firebasestorage.app',
    measurementId: 'G-WGTYR83KMR',
  );
}
